### ISSUE TITLE
Adminisztráció/Gyorsrögzítő

### ISSUE THREAD

**Issue by molnarlaszlo** [molnarlaszlo/unior-rendeles#2]
Minden kért funkció elkészült és kinn van élesen, teszteljétek kérlek.

Használat előtt érdemes: CTRL+Shift+R.

Amennyiben senkinek nincs kifogása akkor ezt a kérdést zárjuk.

**Comment by pitareneyba** [comment]
Huhh. pontosan mik is ezek az elkészült funkciók?
Hogyan tudok új problémát nyitni (nem vagyok még teljesen képben), vagy azt csak Te tudsz a saját nevedben?

**Comment by pitareneyba** [comment]
Megtaláltam, már írom...

**Comment by molnarlaszlo** [comment]
@pitareneyba néhány ami elkészült: 
termék képek láthatók a termékekhez, link elérhető info gombbal a termék oldalára, ár+kedvezmény formázva, kiválasztott szállítási cím is megmarad rögzítés után.

**Comment by pitareneyba** [comment]
@molnarlaszlo Remek! Köszi!
