### ISSUE TITLE
Rendelés Import/Importálás eredménye

### ISSUE THREAD

**Issue by pitareneyba** [molnarlaszlo/unior-rendeles#6]
az Excel import utáni megjelenített adatoknál az "Érvénytelen cikkszám:" esetén baromi fontos lenne - csak vesszővel elválasztva, egymás után - felsorolni, hogy mik azok az érvénytelen cikkszámok? Jelen esetben 45 tételes rendelést vittem fel, abból egy volt helytelen (gondolom valami kifutott termék, ez elég gyakran előfordul). Most egyesével nézegetnem kell soronként, hogy melyik a hibás. Telik az idő...

**Comment by molnarlaszlo** [comment]
Javítva. meg fog jelenni így:
![image](https://user-images.githubusercontent.com/83342987/117124200-50f80d80-ad98-11eb-9a92-2ba1ddd5a340.png)

**Comment by pitareneyba** [comment]
@molnarlaszlo Naggyon Király vagy!

**Comment by molnarlaszlo** [comment]
@pitareneyba 👍
